### ISSUE TITLE
Target closed

### ISSUE THREAD

**Issue by incompletude** [tinovyatkin/nest-puppeteer#161]
I was getting the target close error inside a module using puppeter. I have removed any references to the module inside the providers, and having the module `PuppeteerModule.forRoot(),` is enough to trigger the target close error like bellow:

Any tips?

Strangelly enough, the error doesn't trigger on localhost (macos), only on remote server (linux ubuntu) machine. maybe something related to this?

```
import { BullModule } from "@nestjs/bull"
import { Module } from "@nestjs/common"
import { PuppeteerModule } from "nest-puppeteer"
import { CertificateConsumer } from "~/certificate/certificate.consumer"
import { CertificateController } from "~/certificate/certificate.controller"
import { EnvConfig } from "~/common/env.config"
import { FileModule } from "~/file/file.module"
import { AddressModule } from "~/public-address/address.module"
import { ContactModule } from "~/public-contact/contact.module"
import { MembershipModule } from "~/public-membership/membership.module"
import { NaturalModule } from "~/public-natural/natural.module"
import { PremiumModule } from "~/public-premium/premium.module"
import { UserModule } from "~/public-user/user.module"

@Module({
  imports: [
    BullModule.registerQueue({
      name: "certificate",
      redis: {
        host: EnvConfig.REDIS_HOST,
        port: EnvConfig.REDIS_PORT,
      },
      defaultJobOptions: {
        attempts: 1,
        removeOnComplete: true,
        removeOnFail: false,
      },
    }),
    PuppeteerModule.forRoot(),
    MembershipModule,
    PremiumModule,
    UserModule,
    NaturalModule,
    ContactModule,
    AddressModule,
    FileModule,
  ],
  providers: [CertificateConsumer],
  controllers: [CertificateController],
  exports: [],
})
export class CertificateModule {}
```

```
[Nest] 37   - 10/06/2020, 9:26:14 PM   [ExceptionHandler] Protocol error (Target.setDiscoverTargets): Target closed. +35ms
Error: Protocol error (Target.setDiscoverTargets): Target closed.
    at /app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:63
    at new Promise (<anonymous>)
    at Connection.send (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:70:16)
    at Function.create (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:95:26)
    at ChromeLauncher.launch (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:106:56)
    at async InstanceWrapper.useFactory [as metatype] (/app/node_modules/nest-puppeteer/dist/puppeteer-core.module.js:38:24)
    at async Injector.instantiateClass (/app/node_modules/@nestjs/core/injector/injector.js:294:37)
    at async callback (/app/node_modules/@nestjs/core/injector/injector.js:77:30)
    at async Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:118:24)
    at async Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:81:9)
```

**Comment by incompletude** [comment]
The error is related to the server not having all the required ubuntu libs.

**Comment by LuwanKonnect** [comment]
> The error is related to the server not having all the required ubuntu libs.

how can I fix this issue? what libs should I install?

**Comment by EasonQwQ** [comment]
```
import type { LaunchOptions } from 'puppeteer';
PuppeteerModule.forRoot(

      <LaunchOptions>{
        pipe: true,
        executablePath: '/usr/bin/chromium-browser',
        // args: ['--disable-setuid-sandbox', '--no-sandbox'],
        args: ['--no-sandbox'],
      }, // optional, any Puppeteer launch options here or leave empty for good defaults */,
    ),
```

**Comment by LuwanKonnect** [comment]
> ```
> import type { LaunchOptions } from 'puppeteer';
> PuppeteerModule.forRoot(
> 
>       <LaunchOptions>{
>         pipe: true,
>         executablePath: '/usr/bin/chromium-browser',
>         // args: ['--disable-setuid-sandbox', '--no-sandbox'],
>         args: ['--no-sandbox'],
>       }, // optional, any Puppeteer launch options here or leave empty for good defaults */,
>     ),
> ```

Thanks for your answer, the executablePath will cause error, then I research error find some ticket in puppeteer, which ask me install some dependences in linux, but it won't work. then I comment out that line. And it's works. thanks!
